:Q
FluxML/Optimisers.jl pull request #13
Opened 2021-02-13 12:11 UTC by DhairyaLGandhi

2021-03-11 21:02 UTC, darsnack requested changes
Some typos

2021-03-11 21:02 UTC, darsnack commented on src/mutating.jl
> +function apply(o::RADAM, x, dx, state)
```suggestion
function apply!(o::RADAM, x, dx, state)
```

2021-03-11 21:02 UTC, darsnack commented on src/mutating.jl
> +function apply(o::ADAM{T}, x, dx, state) where T
```suggestion
function apply!(o::ADAM{T}, x, dx, state) where T
```

2021-03-11 21:02 UTC, darsnack commented on src/mutating.jl
> +function apply(o::RMSProp, x, dx, state)
```suggestion
function apply!(o::RMSProp, x, dx, state)
```

2021-03-11 21:02 UTC, darsnack commented on src/mutating.jl
> +function apply(o::Nesterov, x, dx, state)
```suggestion
function apply!(o::Nesterov, x, dx, state)
```

2021-03-11 21:18 UTC, darsnack reviewed
Couple more typos restructuring the state tuple

2021-03-11 21:18 UTC, darsnack commented on src/mutating.jl
> +  (mt, ut), βt = state
```suggestion
  mt, ut, βt = state
```

2021-03-11 21:18 UTC, darsnack commented on src/mutating.jl
> +  (mt, ut), βt = state
```suggestion
  mt, ut, βt = state
```

2021-03-11 21:18 UTC, darsnack commented on src/mutating.jl
> +  (mt, vt), βt, dx_ = state
```suggestion
  mt, vt, βt, dx_ = state
```

2021-03-11 21:18 UTC, darsnack commented on src/mutating.jl
> +  (mt, vt), βt = state.decays
```suggestion
  mt, vt, βt = state
```

2021-03-12 02:11 UTC, darsnack commented on src/mutating.jl
> +end
```suggestion
end

function apply!(o::OptimiserChain, x, dx, states)
  new_states = similar(states)
  for (i, (opt, state)) in enumerate(zip(o.opts, states))
    _, new_states[i] = apply!(opt, x, dx, state)
  end

  return dx, new_states
end
```

2021-03-12 02:11 UTC, darsnack commented on src/mutating.jl
> +  return dx, ((mt, vt), βt .* β)
```suggestion
  return dx, (mt, vt, βt .* β)
```

2021-03-12 02:11 UTC, darsnack commented on src/mutating.jl
> +  return dx, ((mt, vt), βt .* β, dx_)
```suggestion
  return dx, (mt, vt, βt .* β, dx_)
```

2021-03-12 02:11 UTC, darsnack commented on src/mutating.jl
> +  return dx, ((mt, ut), βt .* β)
```suggestion
  return dx, (mt, ut, βt .* β)
```

2021-03-12 02:11 UTC, darsnack commented on src/mutating.jl
> +  return dx, ((mt, ut), βt .* β)
```suggestion
  return dx, (mt, ut, βt .* β)
```

2021-06-15 15:47 UTC, darsnack commented
@DhairyaLGandhi I have rebased this locally, do you mind if I push it?

2021-06-15 15:55 UTC, DhairyaLGandhi commented
I think I wanted to handle this separately. It also seems like some other changes were merged hastily?

2021-06-15 15:57 UTC, darsnack commented
What do you mean handled separately? This has been in need of a rebase for months (any recent changes weren't the reason for preventing this from being merged).

2021-06-15 16:12 UTC, DhairyaLGandhi commented
Mutation isn't the goal - so Handling the code duplication separately. Mutation should not be the default unless it is absolutely needed. The api change also needs to be accounted for.

2021-06-15 16:24 UTC, darsnack commented
I am confused. Do you still want to merge this PR or not? All I want is to merge this PR.

2021-06-15 16:46 UTC, DhairyaLGandhi commented
We can merge it when we need it. We'd prolly not make mutation the default though.

2022-07-26 13:31 UTC, darsnack commented
Superseded by #31.

2022-07-26 13:31 UTC, closed without merging